CREATE TABLE IF NOT EXISTS clima (
    latitud TEXT,
    longitud TEXT,
    altitud_metros FLOAT,
    altitud_pies FLOAT,
    descripcion_clima TEXT,
    codigo_clima INTEGER,
    icono_clima TEXT,
    temperatura_c FLOAT,
    temperatura_f FLOAT,
    sensacion_termica_c FLOAT,
    sensacion_termica_f FLOAT,
    viento_mph INTEGER,
    viento_kmh INTEGER,
    viento_kts INTEGER,
    viento_ms FLOAT,
    direccion_viento_grados INTEGER,
    direccion_viento TEXT,
    nubosidad_pct INTEGER,
    humedad_pct INTEGER,
    punto_rocio_c FLOAT,
    punto_rocio_f FLOAT,
    visibilidad_km FLOAT,
    visibilidad_mi FLOAT,
    presion_mb INTEGER,
    presion_in FLOAT
);
